// Adjectives and descriptors
const adjectives = [
  "happy",
  "sunny",
  "cosmic",
  "stellar",
  "swift",
  "mighty",
  "clever",
  "brave",
  "gentle",
  "noble",
  "quick",
  "bright",
  "silver",
  "golden",
  "crystal",
  "mystic",
  "ancient",
  "modern",
  "electric",
  "magnetic",
  "dynamic",
  "static",
  "flying",
  "dancing",
  "singing",
  "laughing",
  "smiling",
  "glowing",
  "shining",
  "sparkling",
  "dazzling",
  "radiant",
  "peaceful",
  "serene",
  "tranquil",
  "vibrant",
  "energetic",
  "lively",
  "spirited",
  "bold",
  "fearless",
  "curious",
  "wise",
  "witty",
  "charming",
  "elegant",
  "graceful",
  "agile",
  "nimble",
  "speedy",
  "zippy",
  "bouncy",
  "jolly",
  "merry",
  "cheerful",
  "playful",
  "friendly",
  "loyal",
  "honest",
  "kind",
  "warm",
  "cool",
  "chill",
  "awesome",
  "amazing",
  "wonderful",
  "fantastic",
  "magnificent",
  "marvelous",
  "splendid",
  "brilliant",
  "genius",
  "super",
  "mega",
  "ultra",
  "hyper",
  "turbo",
  "quantum",
  "nano",
  "micro",
  "macro",
  "epic",
  "legendary",
  "mythic",
  "heroic",
  "royal",
  "imperial",
  "majestic",
];

// Nouns - animals, objects, nature elements
const nouns = [
  // Animals
  "panda",
  "dolphin",
  "eagle",
  "falcon",
  "hawk",
  "owl",
  "raven",
  "phoenix",
  "dragon",
  "unicorn",
  "griffin",
  "pegasus",
  "lion",
  "tiger",
  "leopard",
  "cheetah",
  "panther",
  "wolf",
  "fox",
  "bear",
  "koala",
  "kangaroo",
  "rabbit",
  "squirrel",
  "hedgehog",
  "otter",
  "seal",
  "whale",
  "shark",
  "octopus",
  "jellyfish",
  "starfish",
  "butterfly",
  "dragonfly",
  "firefly",
  "bee",
  "hummingbird",
  "peacock",
  "flamingo",
  "penguin",

  // Nature elements
  "mountain",
  "valley",
  "river",
  "ocean",
  "forest",
  "desert",
  "glacier",
  "volcano",
  "canyon",
  "meadow",
  "prairie",
  "savanna",
  "tundra",
  "rainforest",
  "waterfall",
  "geyser",
  "aurora",
  "comet",
  "meteor",
  "planet",
  "galaxy",
  "nebula",
  "constellation",
  "star",
  "moon",
  "sun",
  "eclipse",
  "horizon",
  "sunrise",
  "sunset",
  "rainbow",
  "thunder",
  "lightning",
  "storm",
  "breeze",
  "wind",
  "tornado",
  "hurricane",
  "blizzard",
  "avalanche",

  // Cool objects and concepts
  "rocket",
  "satellite",
  "spaceship",
  "explorer",
  "pioneer",
  "voyager",
  "wanderer",
  "nomad",
  "knight",
  "samurai",
  "ninja",
  "wizard",
  "sage",
  "oracle",
  "prophet",
  "champion",
  "guardian",
  "sentinel",
  "watcher",
  "keeper",
  "protector",
  "defender",
  "warrior",
  "hero",
  "artist",
  "painter",
  "sculptor",
  "musician",
  "composer",
  "poet",
  "writer",
  "dreamer",
  "thinker",
  "scholar",
  "scientist",
  "inventor",
  "creator",
  "builder",
  "architect",
  "engineer",
];

// Simple hash function to convert string to number
function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return Math.abs(hash);
}

// Generate a CONSISTENT name mixing 2 random english words given the same string seed
const generateVisitorName = (seed: string): string => {
  // Use the seed to deterministically select words
  const hash = hashString(seed);

  // Use different parts of the hash for each word selection
  const adjectiveIndex = hash % adjectives.length;
  const nounIndex = (hash >> 8) % nouns.length;

  const adjective = adjectives[adjectiveIndex] ?? "anonymous";
  const noun = nouns[nounIndex] ?? "visitor";

  // Capitalize first letter of each word
  const capitalizedAdjective =
    adjective.charAt(0).toUpperCase() + adjective.slice(1);
  const capitalizedNoun = noun.charAt(0).toUpperCase() + noun.slice(1);

  return `${capitalizedAdjective} ${capitalizedNoun}`;
};

export { generateVisitorName };
